---
# Source: kafka-lag-exporter/templates/030-ConfigMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-lag-exporter-1646888313-configmap
  labels:
    app.kubernetes.io/name: kafka-lag-exporter
    helm.sh/chart: kafka-lag-exporter-0.6.8
    app.kubernetes.io/instance: kafka-lag-exporter-1646888313
    app.kubernetes.io/managed-by: Helm
data:
  application.conf: |
    kafka-lag-exporter {
      port = 8000
      poll-interval = 30 seconds
      lookup-table-size = 60
      client-group-id = "kafkalagexporter"
      kafka-client-timeout = 10 seconds
      clusters = [
        {
          name = "lkc-0xr722"
          bootstrap-brokers = "pkc-pgq85.us-west-2.aws.confluent.cloud:9092"
          consumer-properties = {
            sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username='LDMGW4BF4LOA5Z4I' password='xxx';"
            sasl.mechanism = "PLAIN"
            security.protocol = "SASL_SSL"
            ssl.endpoint.identification.algorithm = "https"
          }
          admin-client-properties = {
            sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username='LDMGW4BF4LOA5Z4I' password='xxx';"
            sasl.mechanism = "PLAIN"
            security.protocol = "SASL_SSL"
            ssl.endpoint.identification.algorithm = "https"
          }
          labels = {
          }
        }
      ]
      reporters.prometheus.port = 8000
      sinks = ["PrometheusEndpointSink"]
      watchers = {
        strimzi = "false"
      }
      metric-whitelist = [
        ".*"
      ]
    }

    akka {
      loggers = ["akka.event.slf4j.Slf4jLogger"]
      loglevel = "DEBUG"
      logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
    }
  logback.xml: |
    <configuration>
        <variable name="ROOT_LOG_LEVEL" value="INFO" />
        <variable name="KAFKA_LAG_EXPORTER_LOG_LEVEL" value="INFO" />
        <variable name="KAFKA_LAG_EXPORTER_KAFKA_LOG_LEVEL" value="INFO" />
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%date{ISO8601} %-5level %logger{36} %X{akkaSource} - %msg %ex%n</pattern>
            </encoder>
        </appender>
        <logger name="org.apache.kafka" level="${KAFKA_LAG_EXPORTER_KAFKA_LOG_LEVEL}"/>
        <logger name="com.lightbend.kafkalagexporter" level="${KAFKA_LAG_EXPORTER_LOG_LEVEL}"/>
        <root level="${ROOT_LOG_LEVEL}">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>